openapi: 3.0.0
info:
  title: Login API Ruby
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.0.1
servers:
  - url: http://localhost:4000/
    description: Local
paths:
  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                  example:
                    email: 'hoangnv@ai-t.vn'
                    password: 'Hoang1235'
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema: 
                type: object
                properties: 
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      email:
                        type: string
                      created_at:
                        type: string
                        format: date-time
                      created_date:
                        type: string
                        format: date string
                example:
                  status:
                    code: 200
                    message: 'Logged in sucessfully.'
                  data:
                    id: 1
                    email: 'hoangnv@ai-t.vn'
                    created_at: '2023-08-24T03:20:49.450Z'
                    created_date: '08/24/2023'
  /signup:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                    password_confirm:
                      type: string
                  example:
                    email: 'hoangnv@ai-t.vn'
                    password: 'Hoang1235'
                    password_confirm: 'Hoang1235'
      responses:
        '200':
          description: Sign up success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      email:
                        type: string
                      created_at:
                        type: string
                        format: date-time
                      created_date:
                        type: string
                        format: date
                example:
                  status:
                    code: 200
                    message: 'Signed up sucessfully.'
                  data:
                    id: 1
                    email: 'hoangnv@ai-t.vn'
                    created_at: '2023-08-24T03:20:49.450Z'
                    created_date: '08/24/2023'
        '422':
          description: Sign up fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                example:
                  status:
                    code: 422
                    message: "User couldn't be created successfully."
  /change_password:
    put:
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              example:
                current_password: 'Hoang1235'
                password: 'Hoang123'
                password_confirmation: 'Hoang123'
      responses:
        '200':
          description: Change password success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      email:
                        type: string
                      created_at:
                        type: string
                        format: date-time
                      created_date:
                        type: string
                        format: date
                example:
                  status:
                    code: 200
                    message: 'Change password sucessfully.'
                  data:
                    id: 1
                    email: 'hoangnv@ai-t.vn'
                    created_at: '2023-08-24T03:20:49.450Z'
                    created_date: '08/24/2023'
        '400':
          description: Change password fail
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string
                example:
                  status:
                    code: 400
                    message: "Current password is invalid"
